repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
        exclude: ".devcontainer/devcontainer.json"
      - id: check-yaml
      - id: pretty-format-json
        exclude: ".devcontainer/devcontainer.json"
        args: ["--autofix", "--indent", "4", "--no-sort-keys"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
  - repo: https://github.com/zahorniak/pre-commit-circleci.git
    rev: v0.6 # Ensure this is the latest tag, comparing to the Releases tab
    hooks:
      - id: circleci_validate
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100", "--target-version=py38"]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: bash -c 'git diff --staged -- "$@" | flake8 --diff --ignore=E203,E501,W503 --max-cognitive-complexity=8'
        additional_dependencies:
        - flake8-annotations-complexity==0.0.7
        - flake8-cognitive-complexity==0.1.0
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        verbose: true
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: ["types-requests"]
        exclude: ^(tests|examples)
